// svg icon
export { ReactComponent as Home } from '@icons/home.svg'
export { ReactComponent as Inbox } from '@icons/inbox.svg'
export { ReactComponent as Bookmark } from '@icons/bookmark.svg'
export { ReactComponent as Tag } from '@icons/tag.svg'
export { ReactComponent as Book } from '@icons/book.svg'
export { ReactComponent as Moon } from '@icons/moon.svg'
export { ReactComponent as Message } from '@icons/message.svg'
export { ReactComponent as Heart } from '@icons/heart.svg'
export { ReactComponent as User } from '@icons/user.svg'
export { ReactComponent as Github } from '@icons/github.svg'
export { ReactComponent as Twitter } from '@icons/twitter.svg'
export { ReactComponent as Telegram } from '@icons/telegram.svg'
export { ReactComponent as Music } from '@icons/music.svg'
export { ReactComponent as Mail } from '@icons/mail.svg'
export { ReactComponent as Anchor } from '@icons/anchor.svg'
export { ReactComponent as External } from '@icons/external.svg'
export { ReactComponent as Hash } from '@icons/hash.svg'
export { ReactComponent as Search } from '@icons/search.svg'
export { ReactComponent as Scissors } from '@icons/scissors.svg'
export { ReactComponent as Send } from '@icons/send.svg'
export { ReactComponent as Code } from '@icons/code.svg'
export { ReactComponent as Calendar } from '@icons/calendar.svg'
export { ReactComponent as Eye } from '@icons/eye.svg'

// cloud icon
export { Thunder, Rain, Snow, Sun, Sunshine, Windy } from './Cloud'

// custom icon
export { default as Butterfly } from './Butterfly'
